const skills = [
  {
    animation: "fade-left",
    delay: "300",
    duration: "1200",
    easing: "ease",
    icon: "/skills/html.png",
    title: "Tailwind CSS",
  },
  {
    animation: "fade-left",
    delay: "300",
    duration: "900",
    easing: "ease",
    icon: "/skills/html.png",
    title: "HTML 5",
  },
  {
    animation: "fade-left",
    delay: "300",
    duration: "900",
    easing: "ease",
    icon: "/skills/css.png",
    title: "CSS 3",
  },
  {
    animation: "fade-up",
    delay: "300",
    duration: "900",
    easing: "ease",
    icon: "/skills/js.png",
    title: "Javascript",
  },
  {
    animation: "zoom-in",
    delay: "0",
    duration: "1200",
    easing: "ease-in",
    icon: "/skills/react.png",
    title: "React JS",
  },
  {
    animation: "fade-down",
    delay: "300",
    duration: "900",
    easing: "ease",
    icon: "/skills/node.png",
    title: "Nodejs",
  },
  {
    animation: "fade-right",
    delay: "300",
    duration: "900",
    easing: "ease",
    icon: "/skills/express.png",
    title: "Express",
  },
  {
    animation: "fade-right",
    delay: "300",
    duration: "900",
    easing: "ease",
    icon: "/skills/mongodb.png",
    title: "MongoDB",
  },
  {
    animation: "fade-right",
    delay: "300",
    duration: "1200",
    easing: "ease",
    icon: "/skills/mui.png",
    title: "Material UI",
  },
];

export default skills;
